server:
  port: 8989
  servlet:
    context-path: /springboot-mybatis
    jsp:
      init-parameters:
        development: true
upload:
  dir: D:\\project\\springboot-file #文件上传路径

#http://localhost:8989/springboot-mybatis/index.jsp
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp #修改视图解析器的相关配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 指定连接池类型
    driver-class-name: com.mysql.cj.jdbc.Driver      # 指定驱动 8.0数据库中间得加“cj”
    url: jdbc:mysql://localhost:3306/tianjin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC        # 指定连接的url
    username: root                                # 指定数据库用户名
    password: 123456                          # 指定数据库密码
  resources:
    static-locations: file:${upload.dir}
  servlet:
    multipart:
      max-file-size: 31457280  #上传文件的最大限制
      max-request-size: 31457280  #用来指定服务器最大文件大小

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml   # 指定mapper文件所在的位置
  type-aliases-package: compzx.entity.User   # 指定为哪个包起别名
#也不一定是数据库版本问题，仔细检查代码，der货！！！
logging:
  level:
    root: info